### ISSUE TITLE
set the dist/ folder to none

### ISSUE THREAD

**Issue by omargourari** [austinpray/asset-builder#24]
Hi,
here are my paths in my manifest.json file:
```
	"paths": {
		"source": "public_html/assets/",
		"dist": "public_html/build/"
	},
```
How can I let gulp build scripts/images/fonts/.. folders inside public_html without creating the dist/ folder?

**Comment by austinpray** [comment]
What's your project directory structure?

**Comment by omargourari** [comment]
It's a codeigniter porject with the following folder structure:

application/
system/
public_html/
    assets/
        manifest.json
    components/

**Comment by austinpray** [comment]
Ah okay so:

```
|--application/
|--system/
|--public_html/
|  `--components/
|  `--javascript/
|     `--main.js
|  `--styles/
|     `--main.css
|  `--assets/
|     `--manifest.json
```

in that case:
```json
"paths": {
        "source": "public_html/assets/",
        "dist": "public_html/"
    },
```

Should work for you. However if you have a "clean" task that deletes all the built assets I would be careful: if you have it delete "path.dist" it will delete your source assets as well.

**Comment by omargourari** [comment]
thanks

**Comment by austinpray** [comment]
Everything working?

**Comment by omargourari** [comment]
Yes
tested and eveything is working
thanks
