### ISSUE TITLE
Proper Name?

### ISSUE THREAD

**Issue by austinpray** [austinpray/asset-builder#3]
Somehow I managed to snag asset-builder in NPM, but is there a better name that better describes what this does?

It basically 

1. reads a manifest file 
2. reads third-party dependencies
3. places them all in the correct order
4. then gives you an object with a bunch of globs you can feed into gulp or whatever

**Comment by mAAdhaTTah** [comment]
Xylem? Or phloem? Keeping in the "roots" etc. theme, xylem carries water through a plant while phloem carries sugar. asset pipelines, water pipeline... I dunno, just a thought.
