### ISSUE TITLE
Misspellings in documentation

### ISSUE THREAD

**Issue by austinpray** [austinpray/asset-builder#31]
Copy pasta:

Hi Austin, 

I love the work you are doing, you are doing a great job.  I was browsing the documentation for asset-builder and saw some misspellings:

1)  Bottom of page http://use-asset-builder.austinpray.com/api/module-lib_Manifest-Manifest.html

Example
// if you had a manifest with a dependencies property that looked like:
{
  "app.js": {
    files: [ "scripts/main.js" ],
    vendor: [ "vendor/hello-world.js" ]
  }
  "app.js": {
    files: [ "styles/main.css" ],
    vendor: [ "vendor/hello-world.css" ]
  }
}

The second "app.js" should be "app.css".

---------------

2)  On this page http://use-asset-builder.austinpray.com/api/module-lib_buildGlobs-buildGlobs.html, under Properties for buildGlobs:

bower Object an array of image path glob strings

That description is wrong.  Should be an array of bower component ... (or something like that I'm sure)

**Comment by michaelbeil** [comment]
Had I seen this, I would have helped. Glad you fixed it. My life is now complete.
