### ISSUE TITLE
Remove `austinpray` paths from tests [$5]

### ISSUE THREAD

**Issue by austinpray** [austinpray/asset-builder#47]
For instance [here](https://github.com/austinpray/asset-builder/blob/8f9570e9d4f8ea345c446a28e73234cfa8cd6a5b/test/test.js#L142-145)

```js
  describe('filtering by type', function () {
    it('should get fonts', function () {
      assert.sameMembers(globInstance.filterByType(mockBowerFiles, 'fonts'), normalizeAll([
        "/Users/austinpray/DEV/opensauce/asset-builder/test/tmp/bower_components/bootstrap/fonts/glyphicons-halflings-regular.eot",
        "/Users/austinpray/DEV/opensauce/asset-builder/test/tmp/bower_components/bootstrap/fonts/glyphicons-halflings-regular.svg",
        "/Users/austinpray/DEV/opensauce/asset-builder/test/tmp/bower_components/bootstrap/fonts/glyphicons-halflings-regular.ttf",
        "/Users/austinpray/DEV/opensauce/asset-builder/test/tmp/bower_components/bootstrap/fonts/glyphicons-halflings-regular.woff"
      ]));
    });
```

It is not actually looking anything up by path, it is just comparing the hardcoded input string with the output. However seeing my directory structure is scaring people that are unfamiliar with the tests. 

![screenshot 2015-07-29 15 52 12](https://cloud.githubusercontent.com/assets/2192970/8969538/ca20b386-3609-11e5-8b41-dce5b43c8f39.png)

These should be changed to something like

`/Users/austinpray/DEV/opensauce/asset-builder/test/tmp` -> `/Bogus/app`

**Comment by kalenjohnson** [comment]
No, I think it's bueno like this
