### ISSUE TITLE
possible to specify processManifest.js defaults?

### ISSUE THREAD

**Issue by bkcummins** [austinpray/asset-builder#62]
Trying to use this workflow in the Laravel 5 directory structure so I've specified the following in my gulpfile.

var manifest = require('asset-builder')('./resources/assets/manifest.json');
manifest.paths.source = 'resources/assets/';
manifest.paths.dist = 'public/dist/';

This works except for asset-builder/lib/processManifest.js line #14 hard codes the source path to be 'assets'.  https://github.com/austinpray/asset-builder/blob/master/lib/processManifest.js#L14

I need it to be 'resources/assets' in order to find my scripts, styles, etc.

Is there a way I'm not seeing to feed that path in from settings in the gulpfile?

Thx so much!

**Comment by austinpray** [comment]
If you specify paths in manifest.json it will override.

**Comment by bkcummins** [comment]
that's it....thx!
